import { Navbar } from "@/components/layouts/navigation/navbar";
import { ThemeProvider } from "@/components/layouts/theme-provider";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    disableTransitionOnChange
                >
                    <div className="grid grid-rows-[auto_1fr] min-h-screen w-full max-w-7xl mx-auto">
                        <Navbar />
                        <main className="p-4">{children}</main>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
